//ROOM DETAILS
export const GET_ROOMDETAILS_PENDING = "GET_ROOMDETAILS_PENDING";
export const GET_ROOMDETAILS_SUCCESS = "GET_ROOMDETAILS_SUCCESS";
export const GET_ROOMDETAILS_ERROR = "GET_ROOMDETAILS_ERROR";














//ROOM LIST
export const GET_ROOMLIST_PENDING = "GET_ROOMLIST_PENDING";
export const GET_ROOMLIST_SUCCESS = "GET_ROOMLIST_SUCCESS";
export const GET_ROOMLIST_ERROR = "GET_ROOMLIST_ERROR";

export const POST_ROOMLIST_SUCCESS = "POST_ROOMLIST_SUCCESS";
export const POST_ROOMLIST_PENDING = "POST_ROOMLIST_PENDING";
export const POST_ROOMLIST_ERROR = "POST_ROOMLIST_ERROR";

export const DELETE_ROOMLIST_PENDING = "DELETE_ROOMLIST_PENDING";
export const DELETE_ROOMLIST_SUCCESS = "DELETE_ROOMLIST_SUCCESS";
export const DELETE_ROOMLIST_ERROR = "DELETE_ROOMLIST_ERROR";

export const UPDATE_ROOMLIST_PENDING = "UPDATE_ROOMLIST_PENDING";
export const UPDATE_ROOMLIST_SUCCESS = "UPDATE_ROOMLIST_SUCCESS";
export const UPDATE_ROOMLIST_ERROR = "UPDATE_ROOMLIST_ERROR";







//RESERVATION

export const GET_RESERVATION_PENDING = "GET_RESERVATION_PENDING";
export const GET_RESERVATION_SUCCESS = "GET_RESERVATION_SUCCESS";
export const GET_RESERVATION_ERROR = "GET_RESERVATION_ERROR";


export const POST_RESERVATION_PENDING = "POST_RESERVATION_PENDING";
export const POST_RESERVATION_SUCCESS = "POST_RESERVATION_SUCCESS";
export const POST_RESERVATION_ERROR = "POST_RESERVATION_ERROR";


export const DELETE_RESERVATION_PENDING = "DELETE_RESERVATION_PENDING";
export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS";
export const DELETE_RESERVATION_ERROR = "DELETE_RESERVATION_ERROR";


export const UPDATE_RESERVATION_PENDING = "UPDATE_RESERVATION_PENDING";
export const UPDATE_RESERVATION_SUCCESS = "UPDATE_RESERVATION_SUCCESS";
export const UPDATE_RESERVATION_ERROR = "UPDATE_RESERVATION_ERROR";



